### ISSUE TITLE
Not a Valid Application

### ISSUE THREAD

**Issue by frankgestrada** [nLabs-nScope/nScope-releases#5]
Installed nScope on Windows XP version 2002 Service Pack 3 on a intel core i3 CPU, M370 2.40 GHz 909 MHz, 3.42 GB RAM.

Upon launch I get error "(null) is not a valid Win32 application"

**Comment by pfeerick** [comment]
Unfortunately, that may be due to the dependencies and compile settings used to complete the executables for Windows. Programs that require the Microsoft dot NET framework will give that error message, as will some programs that have not been compiled to run in Windows XP. I'm not having any issues, but I am running Windows 10. I suspect XP will not be supported, unless it is an easy settings change. Windows 7 (or perhaps Vista) is likely to be the oldest version of Windows that will run the nScope software in its current form.

**Comment by mpbiggs** [comment]
Ran nScope on my Win 10 desktop just fine, but also getting "nScope is not a valid Win32 application" when I try to run it on my Win XP laptop. Would be nice to have a solution for this, other than replacing or upgrading my laptop.

**Comment by mpbiggs** [comment]
Thanks!
